# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
