# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_auto_20170911_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
