# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0004_robotid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotid',
            name='robotid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
