# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0005_auto_20170918_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotid',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
